### ISSUE TITLE
Simple Helloworld

### ISSUE THREAD

**Issue by luebken** [upbound/provider-terraform#12]
I'm trying to build a simple helloworld example in multiple steps. This issue / thread is tracking my endeavour and get feedback.  First step is to make sure the provider is running without external resources being provisioned. 

### Variants:
- V1: simply using output: https://github.com/upbound/provider-terraform/issues/12#issuecomment-1327302916
- V2: using terraforms null_resource (not possible)
- ...

**Comment by luebken** [comment]
V1: hello world output

```yaml
# workspace-helloworld.yaml
apiVersion: tf.upbound.io/v1beta1
kind: Workspace
metadata:
  annotations:
    crossplane.io/external-name: test
    meta.upbound.io/example-id: tf/v1beta1/workspace
  name: example-inline
spec:
  forProvider:
    source: Inline
    module: >
      output "hello_world" {
        value = "Hello, World!"
      }
```

```bash 
$ kubectl get workspaces.tf.upbound.io
NAME          READY   SYNCED   AGE
hello-world   True    True     2m5s

$ kubectl get workspaces.tf.upbound.io hello-world -o json | jq .status.atProvider.outputs
{
  "hello_world": "Hello, World!"
}
```

The drawback is cumbersome provider-config: 
```
# provider-config-tf.yaml
apiVersion: tf.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    - filename: gcp-credentials.json
      source: Secret
      secretRef:
        namespace: upbound-system
        name: gcp-creds
        key: credentials
  configuration: |
      // Modules _must_ use remote state. The provider does not persist state.
      terraform {
        backend "kubernetes" {
          secret_suffix     = "providerconfig-default"
          namespace         = "crossplane-system"
          in_cluster_config = true
        }
      }
```

So I wonder if we can make credentials optional or have a way to define credentials without the need to create a secret.
