### ISSUE TITLE
Respect Workspace metadata.name to easily identify managed resources

### ISSUE THREAD

**Issue by PavelPikat** [upbound/provider-terraform#170]
### What problem are you facing?

It looks like Workspace names are auto-generated based on their Claim, and the original metadata.name is completely ignored.
I have the following app in ArgoCD:
![image](https://github.com/upbound/provider-terraform/assets/3666748/1a8beee3-f552-4289-8489-659e98171912)

As you can see, it has 3 workspaces, and their names got randomly auto-generated by the terraform provider.
My hand-crafted names from the Composition are completely ignored.

Here is a piece from composition:
```
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: globaldccs
  labels:
    provider: azure
spec:
  compositeTypeRef:
    apiVersion: someVersion/v1alpha1
    kind: XGlobalDCC
  resources:
    - name: resource-group
      base:
        apiVersion: tf.upbound.io/v1beta1
        kind: Workspace
        metadata:
          name: gdcc-rg # <--- completely ignored
        spec:
          providerConfigRef:
            name: provider-name
          forProvider:
            source: Remote
            module: git::https://bla-bla
            entrypoint: azure/rg
            vars:
              - key: name
              - key: location
```

It would be nice if my custom name would be visible in Kubernetes/ArgoCD so that I could easily identify my resources.

**Comment by bobh66** [comment]
The resource names are automatically generated by Crossplane when the Composite resource is created.  This is to prevent duplicate resource names when multiple claims exist for the same composite.

You can override the metadata.name in a patch, but if the name is not unique you will run into problems when deploying multiple instances of the same Composite,

It is also possible to combine the generated composite name - which should be unique - with your own suffix or prefix, for example:

```
patches:
- type: FromCompositeFieldPath
  fromFieldPath: metadata.name
  toFieldPath: metadata.name
  transforms:
  - type: string
    string:
      fmt: "%s-rg"
```

Using the above example this would give you a Workspace name called `gdcc-infa-9dsc7-rg` which hopefully satisfies the need to uniquely identify the Workspace as well as making it clear which Workspace it represents.
