### ISSUE TITLE
ConfigMap as module source 

### ISSUE THREAD

**Issue by reegnz** [upbound/provider-terraform#179]
### What problem are you facing?

My kubernetes cluster does not have network access to my git server.
Concatenating all of the tf files into a single string and using it with `Inline` is my only option today that doesn't try to pull the module source from a system outside kubernetes (unless I host tar.gz-d modules in-cluster).

### How could Official Terraform Provider help solve your problem?

A more kubernetes-native way would be to support terraform modules stored in configmaps.

If one could define module source to come from a configmap, then it would be very easy to package up an existing terraform module into kubernetes manifests and deploy them like any other kubernetes resource.
This would be a welcome improvement over `Inline` module sources.

Example:

kustomization.yaml:
```yaml
configMapGenerator:
- name: my-terrfaorm-module
  files:
  - main.tf
  - variables.tf
  - outputs.tf
  - versions.tf
```

```sh
kustomize build | kubectl apply -n crossplane-system -
```

workspace.yaml:
```yaml
apiVersion: tf.upbound.io/v1beta1
kind: Workspace
metadata:
  name: my-terraform-module
spec:
  forProvider:
    source: ConfigMap
    module:
      name: my-terraform-module
      namespace: crossplane-system
```

**Comment by ytsarev** [comment]
The feature makes sense! Thanks for documenting it.

**Comment by alkuzad** [comment]
I just use Helm. File.Get loop to include all files inside the inline. Therefore we just copied our current TF structure into folder "terraform" inside a chart. This enables normal TF work if you want to (assuming you extend provider.tf with configuration for the real cloud, provider.tf to be include has to be ONLY for aliases, not for the provider configured in crossplane ProviderConfig).

```
{{/*
Helper to setup Terraform Files

Include like this to ensure proper formatting:

{{ include "compositionTerraform.include" . | trim | indent 14 }}

*/}}
{{- define "compositionTerraform.include" -}}
{{- $currentScope := .}}
{{- with $currentScope}}
{{- range (tuple "provider" "variables" "locals" "data" "main" "outputs") }}
{{- $file := $currentScope.Files.Glob (printf "terraform/%s.tf" .) }}
{{- if $file }}
{{ $currentScope.Files.Get (printf "terraform/%s.tf" .) | trim }}
{{ end -}}
{{- end }}
{{- end }}
{{- end }}
```

**Comment by reegnz** [comment]
Thanks @alkuzad, that sounds like a reasonable alternative.

**Comment by vrabbi** [comment]
this would be extremely beneficial for us as well

**Comment by senare** [comment]
Yes, I would like this to ... 

or atleast the possibility to have a way of including the TF into the *configuration* once I build/bundle crossplane into a OCI image (sry I am not sure of the correct terminology here )

**Comment by joneshf** [comment]
Since this request started with a kustomize example, another workaround is to use [`replacements`](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/replacements/) to substitute a field from a ConfigMap into the `module` field.

If you have a single file, you'd do something like:
```YAML
# kustomization.yaml

configMapGenerator:
  - name: my-terraform-module
    files:
      - main.tf

replacements:
  - source:
      fieldPath: data.[main.tf]
      kind: ConfigMap
      name: my-terraform-module
      version: v1
    targets:
      - fieldPaths:
          - spec.forProvider.module
        select:
          group: tf.upbound.io
          kind: Workspace
          name: my-terraform-module
          version: v1beta1

resources:
  - workspace.yaml
```

```YAML
# workspace.yaml

apiVersion: tf.upbound.io/v1beta1
kind: Workspace
metadata:
  name: my-terraform-module
spec:
  forProvider:
    source: ConfigMap
    module: <Kustomize will replace this with the contents of `main.tf`>
```

I'm not entirely sure how you'd do this with multiple files, but maybe there's some way to concatenate those files into a single string with some other [generator](https://kubectl.docs.kubernetes.io/references/kustomize/glossary/#generator)/[transformer](https://kubectl.docs.kubernetes.io/references/kustomize/glossary/#transformer)? The [`vars`](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/vars/) field seems like it would make that possible, but it's deprecated.
