### ISSUE TITLE
--max-reconcile-rate doesn’t seem to be working on v0.13.0

### ISSUE THREAD

**Issue by cachaldora** [upbound/provider-terraform#234]
### What happened?
I’ve updated terraform provider from version 0.11.0 to 0.13.0 to be able to use pluginCache and parallelism without concurrency issues. With 0.13.0 version I’ve enabled plugin cache and everything seems to be working however reconciliation was taking too long.

As I have -d flag enabled, I was looking into pod logs and noticed that after the upgrade the provider seems to be slow and picking less workloads. The resources used by pod are also significantly less.

### How can we reproduce it?
Configure terraform provider:

```
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: controller-terraform-config
  labels:
    app: provider-terraform
spec:
  args:
    - -d
    - --poll=5m
    - --max-reconcile-rate=40
---
apiVersion: tf.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: provider-terraform-config
  namespace: upbound-system
spec:
  pluginCache: true
```

Create several workspaces and take a look into pod logs and consumed resources. 

### What environment did it happen in?

* Crossplane Version: 1.14.3-up.1
* Provider Version: 0.11.0
* Kubernetes Version: 1.26.10
* Kubernetes Distribution: AKS
