### ISSUE TITLE
Import regular k8s secrets

### ISSUE THREAD

**Issue by prog76** [upbound/provider-terraform#251]
### What problem are you facing?
When one Workspace object writes connection data, it does that as a regular k8s secret. I think it could be a good improvement to make it possible to use this secret as a varFile for the second Workspace objects.

### How could Official Terraform Provider help solve your problem?
probably when Key is omitted, provider could load all keys from the secret as variables:
```
    varFiles:
    - source: SecretKey
      secretKeyRef:
        namespace: default
        name: terraform
```
