### ISSUE TITLE
Terraform variables as JSON object broken

### ISSUE THREAD

**Issue by haraldsk** [upbound/provider-terraform#38]
Setting the string `JSON`  in `spec.forProvider.varFiles[*].format` does not work. 

The provider does not properly interpret the string and writes the configuration file into the provider as  `/tf/<uuid>/crossplane-provider-terraform-0.tfvars` when it should be named `/tf/<uuid>/crossplane-provider-terraform-0.tfvars.json` this causes
terraform to break, because it tries to ingest the JSON formatted variable file as Terraform HCL.

Steps to reproduce: 

1. Create a configmap with JSON data.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-fancy-name
  namespace: default
data:
  provider.tfvars.json: |
    {
      "name": "my-fancy-thing"
    }
```

2. Apply following to composition

```yaml
    - name: terraform-inline-workspace
      base:
        apiVersion: tf.upbound.io/v1beta1
        kind: Workspace
        spec:
          forProvider:
            source: Remote
            module: git::https://github.com/myorg/my-repo
            varFiles:
              - source: ConfigMapKey
                configMapKeyRef:
                  name:  my-fancy-name
                  namespace: default
                  key: provider.tfvars.json
                format: JSON
```

After debugging the provider locally it's likely due to a faulty comparison of memory addresses instead of a regular string comparison. In the following code:

https://github.com/upbound/provider-terraform/blob/40eae2025f8c946b9f992c0f37fb1aea56df8608/internal/controller/workspace/workspace.go#L398

I have tested the patch below and it solved the issue for me:

```diff
@@ -395,10 +396,13 @@ func (c *external) options(ctx context.Context, p v1beta1.WorkspaceParameters) (

        for _, vf := range p.VarFiles {
                fmt := terraform.HCL
-               if vf.Format == &v1beta1.VarFileFormatJSON {
+               if *vf.Format == v1beta1.VarFileFormatJSON {
                        fmt = terraform.JSON
                }
```

I can submit this as a PR if needed.
