### ISSUE TITLE
terraform: `Workspace` CRD is not working with an http backend in gitlab

### ISSUE THREAD

**Issue by ecthelion77** [upbound/provider-terraform#40]
### What happened?

When i try to use an http backend for state on gitlab, I have the following error message in my workspace object :

````
cannot select Terraform workspace: failed to get configured named states: workspaces not supported
````

Configuration is working well when 
* I execute locally on my laptop
* in a gitlab pipeline 
*  manually run with the docker image used by the TF provider :

### How can we reproduce it?

Provider config
```` 
apiVersion: tf.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: >-
      dev-204-cp-az-pim-mgmt:tf.upbound.io/ProviderConfig:cp-az-pim-mgmt/cp-az-pim-mgmt
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"tf.upbound.io/v1beta1","kind":"ProviderConfig","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"dev-204-cp-az-pim-mgmt:tf.upbound.io/ProviderConfig:cp-az-pim-mgmt/cp-az-pim-mgmt"},"labels":{"app.kubernetes.io/instance":"dev-204-cp-az-pim-mgmt","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"cp-az-pim-mgmt","helm.sh/chart":"addons-1.0.0"},"name":"cp-az-pim-mgmt"},"spec":{"configuration":null,"credentials":[{"filename":".git-credentials","secretRef":{"key":".git-credentials","name":"dev-204-cp-az-pim-mgmt-gitlab-pat","namespace":"cp-az-pim-mgmt"},"source":"Secret"},{"filename":"backend.tfvars","secretRef":{"key":"backend.tfvars","name":"dev-204-cp-az-pim-mgmt-gitlab-pat","namespace":"cp-az-pim-mgmt"},"source":"Secret"},{"filename":"azure-provider-config.tf.json","secretRef":{"key":"azure-provider-config.tf.json","name":"dev-204-cp-az-pim-mgmt-az-provider-config","namespace":"cp-az-pim-mgmt"},"source":"Secret"}]}}
  creationTimestamp: '2022-12-19T15:46:40Z'
  finalizers:
    - in-use.crossplane.io
  generation: 5
  labels:
  name: cp-az-pim-mgmt
spec:
  credentials:
    - filename: .git-credentials
      secretRef:
        key: .git-credentials
        name: dev-204-cp-az-pim-mgmt-gitlab-pat
        namespace: cp-az-pim-mgmt
      source: Secret
    - filename: backend.tfvars
      secretRef:
        key: backend.tfvars
        name: dev-204-cp-az-pim-mgmt-gitlab-pat
        namespace: cp-az-pim-mgmt
      source: Secret
    - filename: azure-provider-config.tf.json
      secretRef:
        key: azure-provider-config.tf.json
        name: dev-204-cp-az-pim-mgmt-az-provider-config
        namespace: cp-az-pim-mgmt
      source: Secret
  pluginCache: true
status:
  users: 1
````

Workspace config :
````
apiVersion: tf.upbound.io/v1beta1
kind: Workspace
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: >-
      dev-204-cp-az-pim-mgmt:tf.upbound.io/Workspace:cp-az-pim-mgmt/cp-az-pim-mgmt
    crossplane.io/external-name: aws-clz
  labels:
    app.kubernetes.io/instance: dev-204-cp-az-pim-mgmt
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: cp-az-pim-mgmt
    helm.sh/chart: addons-1.0.0
  name: cp-az-pim-mgmt
spec:
  deletionPolicy: Delete
  forProvider:
    entrypoint: ''
    initArgs:
      - '-backend-config=backend.tfvars'
    module: 'git::https://gitlab.com/xxxxxx/xxxxxxx/xxxxx?ref=master'
    source: Remote
    vars:
      - key: TF_STATE_NAME
        value: default
  providerConfigRef:
    name: cp-az-pim-mgmt
  writeConnectionSecretToRef:
    name: cp-az-pim-mgmt
    namespace: cp-az-pim-mgmt
status:
  atProvider: {}
  conditions:
    - lastTransitionTime: '2022-12-20T10:59:14Z'
      message: >-
        connect failed: cannot select Terraform workspace: failed to get
        configured named states: workspaces not supported
      reason: ReconcileError
      status: 'False'
      type: Synced
````
backend.tfvars :
````
address         = "https://gitlab.com/api/v4/projects/xxxxxxxxxxxxxx/terraform/state/default"
lock_address    = "https://gitlab.com/api/v4/projects/xxxxxxxxxxxxxx/terraform/state/default/lock"
unlock_address  = "https://gitlab.com/api/v4/projects/xxxxxxxxxxxxxx/terraform/state/default/lock"
username        = "xxxxxxxxxxxxxx"
password        = "xxxxxxxxxxxxxx"
lock_method     = "POST"
unlock_method   = "DELETE"
retry_wait_min  = 5
````

### What environment did it happen in?

* Universal Crossplane Version: upbound/crossplane:v1.10.1-up.1
* Provider Version: xpkg.upbound.io/upbound/provider-terraform:v0.2.0
* Cloud provider or hardware configuration : on-premise
* Kubernetes version : 1.22.7
* OS : ubuntu 20.04
