### ISSUE TITLE
terraform: cannot initialize Terraform configuration: unsupported terraform core version

### ISSUE THREAD

**Issue by linuxbsdfreak** [upbound/provider-terraform#41]
### What happened?
Receving the following message 

`cannot initialize Terraform configuration: unsupported terraform core version`

### How can we reproduce it?
main.tf in the root of the repo
```
module "gardener-shoot-aws-cilium-kubectl" {
  source           = "./tf-modules/gardener-shoot-aws-cilium-kubectl"
  gardener_project = var.gardener_project
  cluster_name     = var.cluster_name
  cloud_provider   = var.cloud_provider
  environment      = var.environment
  location         = var.location
  project_name     = var.project_name
  kubernetes_version     = var.kubernetes_version

  providers = {
    kubectl.robot    = kubectl.robot
    kubernetes.robot = kubernetes.robot
  }
}
```

terraform.tf
```                                                      
terraform {
  required_version = "1.3.6"
  required_providers {
    sops = {
      source = "carlpett/sops"
      version = "0.7.1"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "2.16.0"
      configuration_aliases = [ kubernetes.robot, kubernetes.shoot ]
    }
    vault = {
      source  = "hashicorp/vault"
      version = "~> 3.10.0"
      configuration_aliases = [ vault.bootstrap ]
    }
    argocd = {
      source = "oboukili/argocd"
      version = "4.1.0"
    }
    kubectl = {
      source  = "alekc/kubectl"
      version = ">= 2.0.0"
      configuration_aliases = [ kubectl.robot ]
    }
  }
}
```

cp-tf-provider-config.yaml   
```                                     
apiVersion: tf.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: cp-tf-provider-config
  namespace: upbound-system
spec:
  credentials:
  - filename: .git-credentials # use exactly this filename
    source: Secret
    secretRef:
      namespace: upbound-system
      name: git-credentials
      key: .git-credentials
  configuration: |
      terraform {
        backend "kubernetes" {
          secret_suffix     = "cp-tf-state"
          namespace         = "upbound-system"
          in_cluster_config = true
        }
      }
```

cp-tf-workspace.yaml                                                      
```
apiVersion: tf.upbound.io/v1beta1
kind: Workspace
metadata:
  name: cp-tf-remote
  #annotations:
  #meta.upbound.io/example-id: tf/v1beta1/workspace
    # The terraform workspace will be named 'myworkspace'. If you omit this
    # annotation it would be derived from metadata.name - e.g. 'example-remote'.
    #  crossplane.io/external-name: cptfworkspace
spec:
  forProvider:
    initArgs:
      - -upgrade=true
    # Git based remote module is supported.
    # See https://www.terraform.io/language/modules/sources#generic-git-repository
    # and https://www.terraform.io/language/modules/sources#modules-in-package-sub-directories
    # for URL structure.
    # You can also specify a simple main.tf inline; see
    # workspace-inline.yaml.
    source: Remote
    module: "git::https://github.com/myusername/crossplane-terraform.git?ref=main"
    # Variables can be specified inline.
    vars:
    - key: cluster_name
      value: "cptf"
    # Variable files can be loaded from a ConfigMap or a Secret.
    varFiles:
    - source: ConfigMapKey
      configMapKeyRef:
        namespace: cp-tf
        name: cp-tf
        key: cptf.tfvars.json
      # Variables are expected to be in HCL '.tfvars' format by default. Use
      # the JSON format if your variables are in the JSON '.tfvars.json' format.
      format: JSON
  # All Terraform outputs are written to the connection secret.
  providerConfigRef:
    name: cp-tf-provider-config
  writeConnectionSecretToRef:
    namespace: cp-tf
    name: cp-tf-workspace
```

### What environment did it happen in?

* Universal Crossplane Version:  1.10.1-up.1
* Provider Version: xpkg.upbound.io/upbound/provider-terraform:v0.2.0

Include at least the version or commit of Official Terraform Provider you were running. Consider
also including your:

* Cloud provider or hardware configuration
* Kubernetes version (use `kubectl version`)
```
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:25:45Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"darwin/amd64"} Kustomize Version: v4.5.7 Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.7", GitCommit:"e6f35974b08862a23e7f4aad8e5d7f7f2de26c15", GitTreeState:"clean", BuildDate:"2022-10-12T10:50:21Z", GoVersion:"go1.18.7", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes distribution (e.g. Tectonic, GKE, OpenShift) : Gardener
* OS (e.g. from /etc/os-release)
* Kernel (e.g. `uname -a`)
