### ISSUE TITLE
Request credentials example for azurerm provider

### ISSUE THREAD

**Issue by PavelPikat** [upbound/provider-terraform#73]
### What resource do you need?
Example for `azurerm` provider authentication.
Terraform Resource Name: 

### What is your use case?

`azurerm` provider doesn't have an option to authentication using a json file, similar to GPC and AWS examples. It required environment variables, which I can't figure out how to pass from a required `credentials` block with a json file.
Can anyone provider a working example authenticating `azurerm` provider for Azure Cloud?

**Comment by bobh66** [comment]
@PavelPikat environment variables won't work because they apply to all goroutines in the pod/container, not just to the single goroutine that is handling a specific workspace.

Based on the authentication documentation here - https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/service_principal_oidc - it appears that you can configure the provider with the Service Principal auth information directly, so you could store the full provider configuration in a secret and reference it in the providerconfigcredentials block, which will create a credentials.tf file with the data from the secret.  That should allow the provider to authenticate.  I don't have a known-working example but something like this should work:

```
---
apiVersion: tf.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: aws-eu-west-1
spec:
  credentials:
  - filename: credentials.tf
    source: Secret
    secretRef:
      namespace: crossplane-system  # or upbound-system
      name: azure-creds
      key: credentials
  configuration: |
      terraform {
        backend "kubernetes" {
          secret_suffix     = "tf"
          namespace         = "crossplane-system"
          in_cluster_config = true
        }
      }
```

assuming you have a secret with the azure provider block definition as in the terraform Service Principal  documentation.

**Comment by PavelPikat** [comment]
This worked brainly, amazing! Thank you @bobh66

**Comment by danielkimuipath** [comment]
Hi @PavelPikat  @bobh66 , Thank you for the comments. 
Could you please share how you were able to make this work?

I tried to use
```
apiVersion: tf.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    - filename: credentials.tf
      source: Secret
      secretRef:
        namespace: upbound-system
        name: azure-secret-tf
        key: creds
    - filename: .terraformrc
      source: Secret
      secretRef:
        namespace: upbound-system
        name: terraformrc
        key: .terraformrc
    - filename: .git-credentials
      source: Secret
      secretRef:
        namespace: default
        name: git-credentials
        key: .git-credentials
  configuration: |
    terraform {
      backend "kubernetes" {
        secret_suffix     = "tf"
        namespace         = "upbound-system"
        in_cluster_config = true
      }
    }
```

with secret

```
terraform {
  backend "kubernetes" {
    secret_suffix     = "tf"
    namespace         = "upbound-system"
    in_cluster_config = true
  }
  required_version = ">= 1.0.1"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "3.27.0"
    }
  }
}

provider "azurerm" {
  subscriptionId = "value"
  clientId       = "value"
  clientSecret   = "value"
  tenantId       = "value"
  use_oidc = true
  features {}
}

```
workspace
```
apiVersion: tf.upbound.io/v1beta1
kind: Workspace
metadata:
  name: pipeline
spec:
  forProvider:
    source: Inline
    module: |
      resource "azurerm_resource_group" "demo" {
        name     = "test-rg"
        location = "West Europe"
      }
     
      output "url" {
        value = azurerm_resource_group.demo.id
      }
  writeConnectionSecretToRef:
    namespace: default
    name: terraform-workspace-example-inline
```

with this i get the error 

```
Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider
hashicorp/azurerm: cannot search /usr/share/terraform/providers: lstat
/usr/share/terraform/providers: no such file or directory
```

Could you please share an example how you solved this issue? if there something I missed?
