### ISSUE TITLE
Allow use of env variables for providerconfig

### ISSUE THREAD

**Issue by ripro-patrick** [upbound/provider-terraform#96]
### What problem are you facing?
In a regulated environment, we are evaluating the usage of crossplane and the terraform provider.
While evaluating the use of different providerconfigs, we did not find a way to inject environment variables from a secret to the provider config.

Like this here:
https://github.com/crossplane-contrib/provider-aws/blob/master/examples/providerconfig/secret.yaml#L18
```
  credentials:
  - source: Secret
     secretRef:
       namespace: crossplane-system
       name: example-creds
       key: credentials
```

we have tried something like this:
```
  credentials:
  -  source: Secret
      env: MY_ENV_VAR
      secretRef:
        namespace: crossplane-system
        name: example-creds
        key: credentials
```

But currently, it is not possible in the provider-terraform to inject the env variable only. The credential requires you to provide a filename:
https://github.com/upbound/provider-terraform/blob/main/package/crds/tf.upbound.io_providerconfigs.yaml#L112

Trying with filename doesn't seem to do anything:
```
  credentials:
  - source: Secret
     filename: myfilename
     env: MY_ENV_VAR
     secretRef:
       namespace: crossplane-system
       name: example-creds
       key: credentials
```

btw:
supplying a full path or a relative path doesn't work neigther:
```
  credentials:
  - source: Secret
     filename: /mypath/myfilename
     # filename: ./auth/myfilename # doesn't work neither
     secretRef:
       namespace: crossplane-system
       name: example-creds
       key: credentials
```
